services:
  - type: web
    name: shekinah-church-website
    runtime: node
    buildCommand: >
      set -e &&
      echo "Starting build process..." &&
      echo "Current directory: $(pwd)" &&
      echo "Directory contents: $(ls -la)" &&
      cd jsmart1-react &&
      echo "Installing React app dependencies..." &&
      npm install --include=dev &&
      echo "Renaming give.css to Give.css..." &&
      node ../rename-give-css.js &&
      cd .. &&
      echo "Back to root directory. Installing server dependencies..." &&
      npm install &&
      echo "Running build environment check script..." &&
      node check-build-env.js &&
      echo "Checking for case-sensitive imports..." &&
      node check-imports.js &&
      echo "Checking for case-sensitivity issues..." &&
      node check-case-sensitivity.js &&
      echo "Fixing Give.jsx imports..." &&
      node fix-give-imports.js &&
      echo "Running preserve-uploads script..." &&
      node preserve-uploads.js &&
      echo "Running copy-uploads script..." &&
      node copy-uploads.js &&
      echo "Running migrate-images-to-mongodb script..." &&
      node migrate-images-to-mongodb.js &&
      echo "Running restore-images script..." &&
      node restore-images.js &&
      echo "Building React app..." &&
      cd jsmart1-react &&
      npm run build &&
      echo "React build complete. Checking dist directory:" &&
      ls -la dist || echo "ERROR: dist directory not found" &&
      cat dist/index.html || echo "index.html not found or empty" &&
      cd .. &&
      echo "Build process complete. Final directory structure:" &&
      find . -type d -name "dist" | xargs ls -la
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://haithammisape:hrz123@cluster0.jeis2ve.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: PERSISTENT_DIR
        value: /var/data/uploads
      - key: PROJECT_ROOT
        value: /opt/render/project/src
    healthCheckPath: /api/health
